### PR TITLE
Feature/multi target net standard

### PR DESCRIPTION
**Pull request by waxtell**
Relocated the enrichers to a .net standard project and then shared them in a full framework project.  By using conditional compilation pragmas I was able to target both frameworks with a single codebase.

The standard version uses HttpContextAccessor.  The constructor allows an instance to be provided, or, in the absence of an instance, one is created.

The full framework leverages a "fake" HttpContextAccessor which wraps HttpContext.Current.

I suspect the appveyor config may require additional changes, but we can worry about that later, if necessary.

Thank you for your time and consideration!

This is my first time contributing; please be gentle :)

### CODE REVIEW

**Comment by mrstebo** [comment]
I'll take a look at it shortly. Unfortunately I can't approve any PRs anymore :sob: 

But I can poke someone who can :wink:

**Comment by ejcoyle88** [comment]
I'm planning to take a look at this at the weekend, but I don't know much about appveyor, so I can't make much by way of promises. 😆

**Comment by waxtell** [comment]
No worries!  Appveyor is failing now due to an inability to connect to the repo on coveralls.  The solution builds successfully and all of the unit test pass...  we're most of the way there :)

**Comment by ejcoyle88** [comment]
I'm going to merge this on a feature branch, just to see coveralls working. I think the reason it's not working at the moment is because of the secure key. Apparently appveyor doesn't decode them on pull requests.

**Comment by ejcoyle88** [comment]
Seems good once merged :+1:
https://ci.appveyor.com/project/ejcoyle88/serilog-enrichers-correlation-id/build/2.0.0-multi-target-net-standard.1+11.build.6

Will merge in to master now.

**Comment by waxtell** [comment]
Fantastic news!  Thank you for your time and consideration :)

**Pull request merged**
